[package]
name = "dimercore"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Raph Levien <raph@google.com>"]

[dependencies]
serde = "*"
serde_json = "*"

[dependencies.dimer-rope]
path = "rope"
