[package]
name = "xi-core"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Raph Levien <raph@google.com>"]
description = "Main process for xi-core, based on json-rpc"

[dependencies]
serde = "0.8"
serde_json = "0.8"

[dependencies.xi-core-lib]
path = "core-lib"

[dependencies.xi-rpc]
path = "rpc"

[features]
avx-accel = ["xi-rope/avx-accel"]
simd-accel = ["xi-rope/simd-accel"]
